version: "3"

services:
  web:
    build:
      context: .
      args:
        SECRET_KEY: ${SECRET_KEY}
    env_file: .env
    volumes:
      - ./:/opt/webapp:cached
    ports:
      - 8000:${DJANGO_PORT}
  node:
    build:
      context: .
      dockerfile: Dockerfile.node
    stdin_open: true
    tty: true
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api
    volumes:
      - ./src:/app/src:cached
      - ./public:/app/public:cached
    ports:
      - 3000:3000
  postgres:
    environment:
      POSTGRES_PASSWORD: <postgres_pwd>
    volumes:
      - ./postgres-data/postgres:/var/lib/postgresql/data:cached
    ports:
      - "5432:5432"
  redis:
    ports:
      - "6379:6379"
