version: "3"

services:
  web:
    build:
      context: .
      args:
        SECRET_KEY: ${SECRET_KEY}
    env_file: .env
    volumes:
      - ./:/opt/webapp
    ports:
      - "8000:${DJANGO_PORT}"
  node:
    image: "node:12"
    env_file: .env
    volumes:
      - ./:/home/node/app
    ports:
      - "3000:${REACT_PORT}"
    command: "npm start"
  postgres:
    environment:
      POSTGRES_PASSWORD: <postgres_pwd>
    volumes:
      - ./postgres-data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  redis:
    ports:
      - "6379:6379"
